name: "Build Platron"

on:
  workflow_dispatch:
    inputs:
      chosen_os:
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
      build_variant:
        description: Enter build variant here.
        required: true
        default: beta

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ${{github.event.inputs.chosen_os}}
    steps:
      - name: Get the source code.
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies for Platron
        run: npm ci
        shell: bash

      - name: Configute & Build Platron
        run: node scripts/platronMaker.js -b -v=${{github.event.inputs.build_variant}} -d -p=always -w=development
        env: 
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

