name: "Build EAF"
run-name: ${{github.event.inputs.release_channel}}-${{github.event.inputs.update_index}}

on:
  workflow_dispatch:
    inputs:
      chosen_os:
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
      release_channel:
        description: Release channel of this build.
        required: true
        default: beta
      update_index:
        description: Update index of this build.
        required: true
        default: "9999"

jobs:
  build:
    runs-on: ${{github.event.inputs.chosen_os}}
    steps:
      - name: Get the source code.
        uses: actions/checkout@master


      - name: Setup Node.js
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*
    
      - name: Install dependencies for EAF
        run: npm i
        shell: bash

      - name: Build EAF
        run: node scripts/eaf_builder.js -c=${{github.event.inputs.release_channel}} -i=${{github.event.inputs.update_index}} -d -b
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
