name: "Build EAF"
run-name: ${{github.event.inputs.release_channel}}-${{github.event.inputs.update_index}}

on:
  workflow_dispatch:
    inputs:
      chosen_os:
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
      release_channel:
        description: Release channel of this build.
        required: true
        default: beta
      update_index:
        description: Update index of this build.
        required: true
        default: "9999"

jobs:
  build:
    runs-on: ${{github.event.inputs.chosen_os}}
    steps:
      - name: Get the source code.
        uses: actions/checkout@master

      - name: Install dependencies for nvm
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update
              sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          elif [ "$RUNNER_OS" == "Windows" ]; then
              powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash

      - if: runner.os=='Windows'
        run: choco install nvm

      - name: Setup Node.js
        run: nvm use 18.16
    
      - name: Install dependencies for EAF
        run: |
              cd $GITHUB_WORKSPACE/Easy_ADB_fastboot
              npm i
        shell: bash

      - name: Build EAF
        run: |
              cd $GITHUB_WORKSPACE/Easy_ADB_fastboot
              node scripts/eaf_builder.js -c=${{github.event.inputs.release_channel}} -i=${{github.event.inputs.update_index}} -d -b
