name: "Build EAF with beta configs (all platforms)"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*-beta"

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Get the source code.
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies for Platron
        run: npm ci
        shell: bash

      - name: Configure & Build Platron
        run: node scripts/eaf_builder.js -v=beta -d -b -p=always -w=development
        env: 
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}